function JSON2HTML(json) {
    var markdown = ""
    markdown += "# " + json.introduction.basicInformation.projectName + " 测试总结报告\n\n"
    markdown += "## 一、引言\n\n"
    markdown += "### 1.1 基本信息\n\n"
    markdown += "**产品名称：**" + json.introduction.basicInformation.projectName + "\n\n"
    markdown += "**项目承担部门：**" + json.introduction.basicInformation.projectTeam + "\n\n"
    markdown += "**撰写人：**" + json.introduction.basicInformation.writer + "\n\n"
    markdown += "**完成日期：**" + json.introduction.basicInformation.completionDate + "\n\n"
    markdown += "### 1.2 编写目的\n\n"
    markdown += json.introduction.purpose + "\n\n"
    markdown += "### 1.3 参考资料\n\n"
    markdown += json.introduction.reference + "\n\n"
    markdown += "## 二、测试概要\n\n"
    markdown += "<div id=\"testSummaryDiv\"></div>"
    markdown += json.testSummary.addition + "\n\n"
    markdown += "## 三、测试结果\n\n"
    markdown += "### 3.1 Bug分布\n\n"
    markdown += "<div id=\"bugsModuleChartDiv\" style=\"width: 600px;height:400px;\"></div>\n\n"
    markdown += "<div id=\"bugsRateChartDiv\" style=\"width: 600px;height:400px;\"></div>\n\n"
    markdown += "### 3.2 Bug详情\n\n"
    markdown += "### 3.3 Bug分析\n\n"
    markdown += json.testResult.bugsAnalysis + "\n\n"
    markdown += "## 四、测试结论\n\n"
    markdown += json.testConclusion + "\n\n"
    markdown += "## 五、建议\n\n"
    markdown += json.advice + "\n\n"
    return marked(markdown)
}